version: 1.0.{build}
configuration:
- Debug
- Release
- Minimal
platform: x64
build:
  verbosity: minimal
artifacts:
- path: install/sdk
  name: rt64sdk
- path: install/sample
  name: rt64sample
install:
- git submodule init
- git submodule update